name: "build_on_ubuntu"
description: "Build on Ubuntu"
inputs:
  tag_name:
    description: "Tag name"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y gcc \
            qt6-base-dev libqt6svg6-dev qt6-image-formats-plugins fonts-noto-cjk \
            libcurl4-openssl-dev libfreetype-dev fakeroot debhelper libgit2-dev zlib1g-dev \
            libssl-dev cmake
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: v2.8.6
        actions-cache-folder: ubuntu-${{ matrix.ubuntu_ver }}-xmake-cache
    - name: Generate Installer
      shell: bash
      run: |
        packages/debian/package.sh
        cp ../mogan*.deb mogan-research-${{ inputs.tag_name }}-ubuntu-${{ matrix.ubuntu_ver }}-x86_64.deb
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: research-ubuntu-${{ matrix.ubuntu_ver }}
        path: mogan-research-*.deb
